openapi: 3.0.1
info:
  title: Swagger Price 1.0
  description: This is a sample server Price.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://api/price/v1
- url: http://api/price/v1
tags:
- name: price
  description: Everything about your Price
paths:
  /price/{date}/{productId}/{brandId}:
    get:
      tags:
      - price
      summary: Find price by date, productId and brandId
      description: Returns a single Price
      operationId: getPrice
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      - name: productId
        in: path
        required: true
        schema:
          type: integer
      - name: brandId
        in: path
        required: true
        schema:
          type: integer
      - name: time
        in: query
        schema:
          type: string
          pattern: '([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]'
          example: '23:59:59'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Price not found
          content: {}
components:
  schemas:
    Price:
      type: object
      properties:
        brandId:
          type: integer
        productId:
          type: integer
        priceList:
          type: integer
        price:
          type: number
          format: double
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time