swagger: "2.0"
info:
  description: "This is a sample server Price."
  version: "1.0.0"
  title: "Swagger Price 1.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "price.swagger.io"
basePath: "/v1"
tags:
- name: "price"
  description: "Everything about your Price"
schemes:
- "https"
- "http"
paths:
  /price/{date}/{productId}/{brandId}:
    get:
      tags:
      - "price"
      summary: "Find price by date, productId and brandId"
      description: "Returns a single Price"
      operationId: "getPrice"
      produces:
      - "application/json"
      parameters:
      - name: "date"
        in: "path"
        required: true
        type: "string"
        format: "date"
      - name: "productId"
        in: "path"
        required: true
        type: "integer"
      - name: "brandId"
        in: "path"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Price"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Price not found"
definitions:
  Price:
    type: "object"
    properties:
      brandId:
        type: "integer"
      productId:
        type: "integer"
      priceList:
        type: "integer"
      price:
        type: "number"
        format: "double"
      startDate:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"